base:
  experiment_name: ihme_paper
  max_evals: 100 # optimiser evals (trials)
  log: TRUE # fit on log of model_params: ycol
  sd: FALSE # use social distancing covariate for beta
  scoring: mape
  min_days: 4 # min days to train on
  train_size: 20 # train set + val set
  val_size: 6 # val set for hyperopt
  test_size: 30 # test set witheld from model entirely
  shift: 1
  models: [log_erf]
  compartments: [total_infected]
  smooth: 5 # window to smooth data (rolling avg) - 0 means no smoothing
  smooth_jump: FALSE
  smooth_jump_method: weighted
  smooth_jump_days: 33
  verbose: True
run:
  forecast_days: 360
  num_hyperopt: 1 # number of times to run optimiser - done in parallel
backtesting:
  increment: 7 # how often to run backtesting
  forecast_days: 14
model_params:
  xcol: day
  date: date
  groupcol: group
  ycol: deceased
  func: log_erf
  priors: # for when log is TRUE
      fe_init: [-1.1, 16.0, -9.0]
      fe_bounds: [[-5.0, -0.5], [12,40], [-20, -5]]
  pipeline_args:
    n_draws: 20
    cv_threshold: 1.e-2
    smoothed_radius: [7,7]
    num_smooths: 3
    exclude_groups: []
    exclude_below: 0
    exp_smoothing: null
    max_last: null
