base:
  sub_region: null
  region: Italy
  data_source: jhu
  start_date: 02-19-2020
  params_from_csv: False
  params_csv: null
  n_days_optimize: FALSE
  active_log_derf: FALSE
priors:
  log_erf:
    fe_init: [-1.1, 16.0, -9.0]
    fe_bounds: [[-7.0, -0.1], [1, 50], [-40, -1]]