base:
  sub_region: Los Angeles
  region: California
  data_source: ny_times
  start_date: 02-25-2020
  params_from_csv: False
  params_csv: null
  n_days_optimize: FALSE
  active_log_derf: FALSE
priors: 
  log_erf:
    fe_init: [-1.1, 16.0, -9.0]
    fe_bounds: [[-7.0, -0.1], [12,45], [-25, -5]]
