base:
  sub_region: New York City
  region: New York
  data_source: ny_times
  start_date: 03-01-2020
  params_from_csv: True
  params_csv: new_york_city_log_erf_params.csv
  n_days_optimize: FALSE
  active_log_derf: FALSE
priors:
  log_erf:
    fe_init: [-1.1, 16.0, -9.0]
    fe_bounds: [[-7.0, -0.1], [1, 50], [-40, -1]]