# fits to mortality rate, not log(mortality rate)
base:
  log: FALSE
model_params:
  ycol: mortality
  func: erf
  priors: # for when log is FALSE
    fe_init: [0.01, 3.2, 0.5]
    fe_bounds: [[-10, 0], [1, 100], [3, 5]]
