experiment_name: compartmental_paper
train_period: 30 # length of train period
val_period: 30 # length of val period
test_period: 0 # length of test period
num_evals: 1000 # number of evals
which_compartments: [total_infected] # compartments to fit to
models: [sir] # compartmental models used in experiments
shift: 1 # number of days to shift forward if there are multiple runs
verbose: True
align: False
params_from_csv: False
params_sir:
  lockdown_R0: [0.5, 3.5]
  T_inf: [1, 20]
  I_tot_ratio: [0, 20]