sub_region: Los Angeles
region: California
data_source: ny_times
start_date: 02-25-2020
params_from_csv: False
params_csv: null
synth:
  synth_data_path: null
  synth_model: log_erf
  synth_addition: 5
params_sir:
  lockdown_R0: [0.5, 3.5]
  T_inf: [1, 20]
  I_tot_ratio: [0, 20]
