base:
  disable_tracker: FALSE # use athena instead of covid19api
  use_synthetic: TRUE # if True, use synthetic data to train c2 model
  use_actual: TRUE # if True, use actual data to train c2 model
  allowance: 5 # number of days of ground data before train split to prevent nan when rolling average is taken
  s1: 20 # length of series s1
  s2: 5 # length of series s2
  s3: 7 # length of series s3
  shift: 0 # number of days to shift forward in each run
  i1_val_size: 6 # val period for IHME model
  c2_train_period: 20 # train period of c2 compartmental model
  c3_train_period: 20 # train period of c3 baseline compartmental model
  num_evals: 1500 # number of evals for compartmental models
  shift_period: 4 # number of periods to shift forward in each run
  which_compartments: [deceased] # compartments to fit to
  replace_compartments: [deceased] # compartments to use synthetic data for
  compartmental_models: [seirt] # compartmental models used in experiments
params_seirt_tp_7:
  lockdown_R0: [1, 1.5]
  T_inc: [4, 15]
  T_inf: [3, 6]
  T_recov_severe: [5, 60]
  T_recov_fatal: [0, 45]
  P_fatal: [0, 0.3]
  E_hosp_ratio: [0, 2]
  I_hosp_ratio: [0, 1]
params_sird_tp_7:
  lockdown_R0: [1, 6]
  T_inc: [4, 20]
  T_inf: [10, 60]
  T_fatal: [200, 500]
params_seirt_tp_20:
  lockdown_R0: [0.5, 1.5]
  T_inc: [4, 15]
  T_inf: [3, 6]
  T_recov_severe: [5, 60]
  T_recov_fatal: [0, 45]
  P_fatal: [0, 0.3]
  E_hosp_ratio: [0, 2]
  I_hosp_ratio: [0, 1]
params_sird_tp_20:
  lockdown_R0: [1, 3]
  T_inc: [4, 15]
  T_inf: [10, 60]
  T_fatal: [100, 500]