base:
  sub_region: null
  region: Delhi
  s1: 20
  s2: 5
  s3: 7
  shift: 0
  i1_val_size: 6
  c2_train_period: 20
  c3_train_period: 20
  data_source: rootnet
params_seirt_tp_7:
  lockdown_R0: [1, 2.5]
  T_inc: [4, 20]
  T_inf: [2, 10]
  T_recov_severe: [5, 60]
  T_recov_fatal: [0, 200]
  P_fatal: [0, 0.3]
  E_hosp_ratio: [0, 2]
  I_hosp_ratio: [0, 1]
params_sird_tp_7:
  lockdown_R0: [1, 6]
  T_inc: [4, 50]
  T_inf: [5, 60]
  T_fatal: [100, 2000]
params_seirt_tp_20:
  lockdown_R0: [0.5, 2.5]
  T_inc: [2, 15]
  T_inf: [2, 15]
  T_recov_severe: [5, 60]
  T_recov_fatal: [0, 150]
  P_fatal: [0, 0.3]
  E_hosp_ratio: [0, 2]
  I_hosp_ratio: [0, 1]
params_sird_tp_20:
  lockdown_R0: [1, 6]
  T_inc: [4, 30]
  T_inf: [5, 60]
  T_fatal: [100, 2000]