base:
  sub_region: null
  region: Italy
  s1: 30
  s2: 30
  s3: 7
  shift: 26
  i1_val_size: 6
  c2_train_period: 20
  c3_train_period: 20
  data_source: jhu
params_seirt:
  lockdown_R0: [1, 1.15]
  T_inc: [3, 4]
  T_inf: [4, 5]
  T_recov_severe: [5, 60]
  T_recov_fatal: [0, 40]
  P_fatal: [0, 0.3]
  E_hosp_ratio: [0, 2]
  I_hosp_ratio: [0, 1]
params_seirt_tp_7:
  lockdown_R0: [1, 2.5]
  T_inc: [2, 15]
  T_inf: [2, 10]
  T_recov_severe: [5, 60]
  T_recov_fatal: [0, 150]
  P_fatal: [0, 0.4]
  E_hosp_ratio: [0, 3]
  I_hosp_ratio: [0, 1]
params_sird_tp_7:
  lockdown_R0: [1, 6]
  T_inc: [4, 30]
  T_inf: [5, 60]
  T_fatal: [0, 1000]
params_seirt_tp_20:
  lockdown_R0: [0.5, 4]
  T_inc: [4, 20]
  T_inf: [2, 15]
  T_recov_severe: [5, 60]
  T_recov_fatal: [0, 150]
  P_fatal: [0, 0.3]
  E_hosp_ratio: [0, 3]
  I_hosp_ratio: [0, 1]
params_sird_tp_20:
  lockdown_R0: [1, 7]
  T_inc: [4, 50]
  T_inf: [5, 60]
  T_fatal: [100, 600]