base:
  sub_region: null
  region: Italy
  s1: 30
  s2: 5
  s3: 30
  start_date: 02-19-2020
  i1_val_size: 6
  c2_train_period: 20
  c3_train_period: 20
  data_source: jhu
  ihme_config: ../ihme/config/italy.yaml
  seir_config: ../seir/config/italy.yaml
  params_from_csv: True
  params_csv: italy_log_erf_params.csv
priors:
  log_erf:
    fe_init: [-1.1, 16.0, -9.0]
    fe_bounds: [[-7.0, -0.1], [1, 50], [-40, -1]]
  log_derf:
    fe_init: [-1.1, 16.0, -9.0]
    fe_bounds: [[-5.0, -0.5], [12,40], [-20, -5]]
  log_expit:
    fe_init: [-1.1, 16.0, -9.0]
    fe_bounds: [[-5.0, -0.5], [12,40], [-20, -5]]
params_sir:
  lockdown_R0: [0.5, 3.5]
  T_inf: [1, 20]
  I_hosp_ratio: [0, 15]
