base:
  district: Pune
  state: Maharashtra
  disable_tracker: FALSE
  use_synthetic: TRUE
  use_actual: TRUE
  allowance: 5
  s1: 20
  s2: 5
  s3: 7
  shift: 0
  i1_val_size: 6
  c2_train_period: 20
  c3_train_period: 20
  num_evals: 1500
  shift_period: 4
  replace_compartments: [deceased]
params_seirt_tp_7:
  lockdown_R0: [1, 1.5]
  T_inc: [4, 15]
  T_inf: [3, 6]
  T_recov_severe: [5, 60]
  T_recov_fatal: [0, 45]
  P_fatal: [0, 0.3]
  E_hosp_ratio: [0, 2]
  I_hosp_ratio: [0, 1]
params_sird_tp_7:
  lockdown_R0: [1, 6]
  T_inc: [4, 20]
  T_inf: [10, 60]
  T_fatal: [200, 500]
params_seirt_tp_20:
  lockdown_R0: [0.5, 1.5]
  T_inc: [4, 15]
  T_inf: [3, 6]
  T_recov_severe: [5, 60]
  T_recov_fatal: [0, 45]
  P_fatal: [0, 0.3]
  E_hosp_ratio: [0, 2]
  I_hosp_ratio: [0, 1]
params_sird_tp_20:
  lockdown_R0: [1, 3]
  T_inc: [4, 15]
  T_inf: [10, 60]
  T_fatal: [100, 500]