base:
  district: Pune
  state: Maharashtra
  disable_tracker: FALSE
  use_synthetic: TRUE
  use_actual: TRUE
  allowance: 5
  s1: 20
  s2: 5
  s3: 7
  shift: 0
  i1_val_size: 6
  c2_train_period: 20
  c3_train_period: 20
  num_evals: 1500