fitting:
    data:
        data_source: covid19india
        stratified_data: FALSE
        dataloading_params:
            reload_data: FALSE
            state: Maharashtra
            district: Mumbai
            use_dataframe: data_all
        smooth_jump: TRUE
        smooth_jump_params:
            2020-05-28: [null, recovered, active, FALSE, weighted-mag]
            2020-06-14: [null, recovered, active, FALSE, weighted-mag]
            2020-06-15: [null, recovered, active, FALSE, weighted-mag]
            2020-06-23: [2020-06-15, recovered, active, FALSE, weighted-mag]
            2020-06-24: [2020-06-15, recovered, active, FALSE, weighted-mag]
            2020-07-01: [2020-05-28, recovered, active, FALSE, weighted-mag]
            2020-06-15: [null, deceased, total, TRUE, weighted-mag]
        rolling_average: TRUE
        rolling_average_params:
            center: TRUE
            window_size: 7
            win_type: null
            min_periods: 7
            split_after_rolling: FALSE
        log: TRUE
        covariates: ['default_cov', 'default_cov', 'default_cov']
    model: IHME
    default_params:
        N: 1.0e+7
    fitting_method_params:
        num_evals: 100
        num_trials: 1
        seed: 42
    #Choose Fitting Periods and num evaluations
    split:
        start_date: null
        end_date: 2020-06-30
        train_period: 21
        val_period: 7
        test_period: 5
    #Optimisation related parameters
    loss:
        loss_method: mape
        loss_compartments: [total]
        loss_weights: [1]
    model_params:
        xcol: day
        date: date
        groupcol: group
        ycol: total
        func: log_erf
        priors: # for when log is TRUE
            fe_init: [-1.1, 16.0, -9.0]
            fe_bounds: [[-5.0, -0.5], [12,40], [-20, -5]]
        pipeline_args:
            n_draws: 20
            cv_threshold: 1.e-2
            smoothed_radius: [7,7]
            num_smooths: 3
            exclude_groups: []
            exclude_below: 0
            exp_smoothing: null
            max_last: null
forecast:
    forecast_days: 30
logging:
    experiment_name: wiai-temp
    run_name: null
