fitting:
  data:
    data_columns:
    - total
    - active
    - recovered
    - deceased
    dataloader: AthenaLoader
    dataloading_params:
      cache_dir: ../../misc/cache/
      district: Mumbai
      label: mumbai
      pyathena_rc_path: ../../misc/pyathena/pyathena.rc
      reload_data: false
      schema: city_data_mumbai
      staging_dir: mumbai
      state: Maharashtra
      stratified_data: false
      tables:
      - bed_summaries
      - case_summaries
      - testing_summary
    rolling_average: true
    rolling_average_params:
      center: true
      min_periods: 7
      split_after_rolling: false
      win_type: null
      window_size: 7
    smooth_jump: true
    smooth_jump_params:
      '2020-05-28':
      - null
      - recovered
      - active
      - false
      - weighted-mag
      '2020-06-14':
      - null
      - recovered
      - active
      - false
      - weighted-mag
      '2020-06-15':
      - null
      - deceased
      - total
      - false
      - weighted-mag
      '2020-06-23':
      - '2020-06-15'
      - recovered
      - active
      - false
      - weighted-mag
      '2020-06-24':
      - '2020-06-15'
      - recovered
      - active
      - false
      - weighted-mag
      '2020-07-01':
      - '2020-05-28'
      - recovered
      - active
      - false
      - weighted-mag
  default_params:
    N: 10000000.0
  forecast:
    forecast_days: 45
  loss:
    loss_compartments:
    - total
    - active
    - recovered
    - deceased
    loss_method: mape
    loss_weights:
    - 0.25
    - 0.25
    - 0.25
    - 0.25
  model: SEIRHD
  model_family: seir
  optimiser: BO_Hyperopt
  optimiser_params:
    algo: tpe
    num_evals: 2000
    seed: 400
  split:
    end_date: null
    start_date: '2020-05-05'
    test_period: 0
    train_period: 21
    val_period: 3
  variable_param_ranges:
    E_hosp_ratio:
    - - 0
      - 2
    - uniform
    I_hosp_ratio:
    - - 0
      - 1
    - uniform
    P_fatal:
    - - 0
      - 0.1
    - uniform
    T_inc:
    - - 4
      - 5
    - uniform
    T_inf:
    - - 3
      - 4
    - uniform
    T_recov:
    - - 0
      - 40
    - uniform
    T_recov_fatal:
    - - 0
      - 40
    - uniform
    lockdown_R0:
    - - 0.7
      - 1.2
    - uniform
logging:
  experiment_name: wiai-temp
  run_name: null
plotting:
  left_truncation_buffer: 7
  num_trials_to_plot: 10
  pair_fits_to_plot:
  - - best
    - ensemble_mean
  - - ensemble_mean
    - 50
  - - 50
    - 80
  plot_ptiles_for_columns:
  - total
  - active
  - recovered
  - deceased
  plot_topk_trials_for_columns:
  - total
  - active
  - recovered
  - deceased
  right_truncation_buffer: forecast_days
  separate_compartments_separate_ax: true
  truncate_series: true
uncertainty:
  method: ABMAUncertainty
  uncertainty_params:
    construct_percentiles_day_wise: true
    date_of_sorting_trials: null
    fitting_method: gridsearch
    fitting_method_params:
      n_jobs: 10
      parallelise: false
    loss:
      loss_compartments:
      - total
      - active
      - recovered
      - deceased
      loss_method: mape
      loss_weights:
      - 0.25
      - 0.25
      - 0.25
      - 0.25
    percentiles:
    - 2.5
    - 5
    - 10
    - 20
    - 30
    - 40
    - 50
    - 60
    - 70
    - 80
    - 90
    - 95
    - 97.5
    sort_trials_by_column: total
    variable_param_ranges:
      beta:
      - - 0
        - 10
      - 101
    which_fit: m1
