# Driver config has three parts:
#   configs: list of base config names
#   iterate: condensed partial config with choices used across all base configs
#   constant: condensed partial config with choices specific to each base config

# Each terminal element has the structure [pattern, choices, select]
# pattern: the method of specification of the choices
#   - list: list of choices
#   - repeat: value, num_repetitions
#   - range: start, stop (exclusive), step
#   - date_range: start, stop, periods, freq (specify EXACTLY three as per pd.date_range)
# choices: representation of values using one of the above patterns
# select: if True, produce combinations for this element else use default value from base config

# Use generate_configs_from_driver (utils/generic/config.py) to generate all configs.

configs: [default]
iterate:
    fitting:
        split:
            train_period: [repeat, [21, 3], FALSE]
            starting_period: [list, [2020-05-01, 2020-05-22, 2020-06-12, 2020-07-03, 2020-07-24, 2020-08-14, 2020-09-04, 2020-09-25, 2020-10-16, 2020-11-06, 2020-11-27, 2020-12-18, 2021-01-08, 2021-01-29, 2021-02-19], TRUE]
constant:
    default:
        fitting:
            split:
                train_period: [list, [21], TRUE]
            optimiser: [list, [BO_Hyperopt], TRUE]
            optimiser_params:
                num_evals: [list, [3000], TRUE]
                algo: [list, [tpe], TRUE]
                seed: [list, [42], TRUE]
        uncertainty:
            method: [list, [ABMAUncertainty], TRUE]
            uncertainty_params:
                construct_percentiles_day_wise: [list, [TRUE], TRUE]
                date_of_sorting_trials: [list, [null], TRUE]
