fitting:
    data:
        dataloader: Covid19IndiaLoader
        dataloading_params:
            reload_data: FALSE
            stratified_data: FALSE
            cache_dir: "../../misc/cache/"
            state: Maharashtra
            district: Mumbai
            use_dataframe: data_all
        data_columns: [total, active, recovered, deceased]
        smooth_jump: TRUE
        smooth_jump_params:
            2020-05-28: [null, recovered, active, FALSE, weighted-mag]
            2020-06-14: [null, recovered, active, FALSE, weighted-mag]
            2020-06-23: [2020-06-15, recovered, active, FALSE, weighted-mag]
            2020-06-24: [2020-06-15, recovered, active, FALSE, weighted-mag]
            2020-07-01: [2020-05-28, recovered, active, FALSE, weighted-mag]
            2020-06-15: [null, deceased, total, TRUE, weighted-mag]
        rolling_average: TRUE
        rolling_average_params:
            center: TRUE
            window_size: 7
            win_type: null
            min_periods: 7
            split_after_rolling: FALSE
    model_family: seir
    model: SEIRHD
    variable_param_ranges:
        lockdown_R0: [[0.7, 1.2], uniform]
        T_inc: [[4, 5], uniform]
        T_inf: [[3, 4], uniform]
        T_recov: [[0, 40], uniform]
        T_recov_fatal: [[0, 40], uniform]
        P_fatal: [[0, 0.1], uniform]
        E_hosp_ratio: [[0, 2], uniform]
        I_hosp_ratio: [[0, 1], uniform]
    default_params:
        N: 1.0e+7
    optimiser: BO_Hyperopt
    optimiser_params:
        num_evals: 1000
        algo: tpe
        seed: 42
    split:
        start_date: null
        end_date: 2020-10-31
        train_period: 30
        val_period: 3
        test_period: 0
    loss:
        loss_method: mape
        loss_compartments: [total, active, recovered, deceased]
        loss_weights: [0.25, 0.25, 0.25, 0.25]
    forecast:
        forecast_days: 30
plotting:
    truncate_series: TRUE
    left_truncation_buffer: 7
    right_truncation_buffer: forecast_days
    separate_compartments_separate_ax: TRUE
    num_trials_to_plot: 10
    pair_fits_to_plot: [[best, ensemble_mean], [ensemble_mean, 50], [50, 80]]
    plot_topk_trials_for_columns: [total, active, recovered, deceased]
    plot_ptiles_for_columns: [total, active, recovered, deceased]
uncertainty:
    method: ABMAUncertainty
    uncertainty_params:
        which_fit: m1
        fitting_method: gridsearch
        fitting_method_params:
            parallelise: FALSE
            n_jobs: 10
        variable_param_ranges:
            beta: [[0, 10], 101]
        construct_percentiles_day_wise: FALSE
        date_of_sorting_trials: 2020-11-30
        sort_trials_by_column: total
        loss:
            loss_method: mape
            loss_compartments: [total, active, recovered, deceased]
            loss_weights: [0.25, 0.25, 0.25, 0.25]
        percentiles: [2.5, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 97.5]
logging:
    experiment_name: wiai-temp
    run_name: null
