fitting:
    # Geographical Location
    state: 'Maharashtra'
    district: 'Mumbai'
    #Data
    data_from_tracker: False
    granular_data: True
    filename: None
    smooth_jump: TRUE
    #Choose Model and Ranges
    model: SEIRHD
    variable_param_ranges:  
        lockdown_R0: [1, 1.15]
        T_inc: [4, 5]
        T_inf: [3, 4]
        T_recov_severe: [0, 40]
        T_recov_fatal: [0, 40]
        P_fatal: [0, 0.1]
        E_hosp_ratio: [0, 2]
        I_hosp_ratio: [0, 1]
    default_params:
        N: 1.0e+7
        lockdown_date: 2020-03-25
        lockdown_removal_date: 2020-06-30
    #Choose Fitting Periods and num evaluations
    train_period: 7
    val_period: 7
    test_period: 0
    num_evals: 1000
    initialisation: 'intermediate'
    #Optimisation related parameters
    which_compartments: ['total', 'active', 'recovered', 'deceased', 'asymptomatic', 'symptomatic', 'critical']
forecast:
    forecast_days: 30
    num_trials_to_plot: 10
    plot_topk_trials_for_columns: [confirmed, active, symptomatic, asymptomatic]
    plot_ptiles_for_columns: [confirmed, active, symptomatic, asymptomatic]
uncertainty:
    method: MCUncertainty
    uncertainty_params:
        num_evals: 100
        date_of_sorting_trials: 2020-07-31
        sort_trials_by_column: confirmed
        loss_compartments: ['total', 'active', 'recovered', 'deceased']

    
