fitting:
    # Geographical Location
    data:
        data_source: covid19india
        stratified_data: FALSE
        dataloading_params:
            state: Maharashtra
            district: Mumbai
            use_dataframe: data_all
        smooth_jump: TRUE
        rolling_average: TRUE
        rolling_average_params:
            center: TRUE
            window_size: 7
            win_type: None
    #Choose Model and Ranges
    model: SEIRHD
    variable_param_ranges:
        lockdown_R0: [[1, 1.15], uniform]
        T_inc: [[4, 5], uniform]
        T_inf: [[3, 4], uniform]
        T_recov_severe: [[0, 40], uniform]
        T_recov_fatal: [[0, 40], uniform]
        P_fatal: [[0, 0.1], uniform]
        E_hosp_ratio: [[0, 2], uniform]
        I_hosp_ratio: [[0, 1], uniform]
    default_params:
        N: 1.0e+7
        lockdown_date: 2020-03-25
        lockdown_removal_date: 2020-08-30
    fitting_method: bayes_opt
    fitting_method_params:
        num_evals: 1000
        algo: tpe
    #Choose Fitting Periods and num evaluations
    split:
        train_period: 21
        val_period: 7
        test_period: 0
    #Optimisation related parameters
    loss:
        loss_method: mape
        loss_compartments: [total, active, recovered, deceased]
        loss_weights: [0.25, 0.25, 0.25, 0.25]
sensitivity:
    lockdown_R0: [[[1, 1.5], 101], total, None]
    I_hosp_ratio: [[[0, 1], 201], total, None]
    E_hosp_ratio: [[[0, 2], 201], total, None]
    P_moderate: [[[0, 0.5], 201], symptomatic, total]
    P_severe: [[[0, 0.5], 201], critical, total]
    P_fatal: [[[0, 0.5], 201], deceased, total]
    T_recov_mild: [[[1, 100], 101], asymptomatic, total]
    T_recov_moderate: [[[1, 100], 101], symptomatic, total]
    T_recov_severe: [[[1, 100], 101], critical, total]
    T_recov_fatal: [[[1, 100], 101], deceased, total]
forecast:
    forecast_days: 30
    num_trials_to_plot: 10
    plot_topk_trials_for_columns: [total, active]
    plot_ptiles_for_columns: [total, active]
uncertainty:
    method: MCUncertainty
    uncertainty_params:
        num_evals: 100
        date_of_sorting_trials: 2020-08-31
        sort_trials_by_column: total
        loss:
            loss_method: mape
            loss_compartments: [total, active, recovered, deceased]
            loss_weights: [0.25, 0.25, 0.25, 0.25]

    
