fitting:
    # Geographical Location
    data:
        data_source: covid19india
        stratified_data: FALSE
        dataloading_params:
            state: Jharkhand
            district: Ranchi
            use_dataframe: data_all
        smooth_jump: FALSE
        smooth_jump_params: null
        rolling_average: TRUE
        rolling_average_params:
            center: TRUE
            window_size: 7
            win_type: null
            min_periods: 3
            split_after_rolling: FALSE
    #Choose Model and Ranges
    model: SEIRHD
    variable_param_ranges:
        lockdown_R0: [[0.7, 1.7], uniform]
        T_inc: [[4, 5], uniform]
        T_inf: [[3, 4], uniform]
        T_recov: [[0, 40], uniform]
        T_recov_fatal: [[0, 40], uniform]
        P_fatal: [[0, 0.1], uniform]
        E_hosp_ratio: [[0, 2], uniform]
        I_hosp_ratio: [[0, 1], uniform]
    default_params:
        N: 1.4e+6
    fitting_method: bayes_opt
    fitting_method_params:
        num_evals: 100
        algo: tpe
    #Choose Fitting Periods and num evaluations
    split:
        start_date: null
        end_date: 2020-09-27
        train_period: 10
        val_period: 3
        test_period: 0
    #Optimisation related parameters
    loss:
        loss_method: mape
        loss_compartments: [total, active, recovered, deceased]
        loss_weights: [0.25, 0.25, 0.25, 0.25]
sensitivity:
    lockdown_R0: [[[0.5, 1.5], 101], total, null]
    I_hosp_ratio: [[[0, 1], 201], total, null]
    E_hosp_ratio: [[[0, 2], 201], total, null]
    P_fatal: [[[0, 0.5], 201], deceased, total]
    T_recov: [[[1, 100], 101], recovered, total]
    T_recov_fatal: [[[1, 100], 101], deceased, total]
forecast:
    forecast_days: 45
    num_trials_to_plot: 10
    plot_topk_trials_for_columns: [total, active]
    plot_ptiles_for_columns: [total, active]
uncertainty:
    method: MCUncertainty
    uncertainty_params:
        num_evals: 150
        num_evals: 100
        which_fit: m2
        variable_param_ranges:
            beta: [[0, 15], uniform]
        date_of_sorting_trials: 2020-10-12
        sort_trials_by_column: total
        loss:
            loss_method: mape
            loss_compartments: [total, active, recovered, deceased]
            loss_weights: [0.25, 0.25, 0.25, 0.25]
        percentiles: [2.5, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 97.5]
