fitting:
    data:
        dataloader: SimulatedDataLoader
        stratified_data: FALSE
        dataloading_params:
            reload_data: FALSE
            cache_dir: "../../misc/cache/"
            state: Maharashtra
            district: Mumbai
            use_dataframe: data_all
            generate: TRUE
            config_file: seir_pu_fixed.yaml
            filename: ../../data/data/simulated_data/undetected.csv
        data_columns: [total, active, recovered, deceased]
        smooth_jump: FALSE
        smooth_jump_params:
            2020-05-28: [null, recovered, active, FALSE, weighted-mag]
            2020-06-14: [null, recovered, active, FALSE, weighted-mag]
            2020-06-23: [2020-06-15, recovered, active, FALSE, weighted-mag]
            2020-06-24: [2020-06-15, recovered, active, FALSE, weighted-mag]
            2020-07-01: [2020-05-28, recovered, active, FALSE, weighted-mag]
            2020-06-15: [null, deceased, total, TRUE, weighted-mag]
        rolling_average: FALSE
        rolling_average_params:
            center: TRUE
            window_size: 7
            win_type: null
            min_periods: 1
            split_after_rolling: FALSE # NOT IMPLEMENTED
    model_family: seir
    model: SEIR_PU
    variable_param_ranges:
        T_inc: [[4, 6], uniform]
        T_inf_U: [[1, 20], uniform]
        T_recov: [[1, 40], uniform]
        T_recov_fatal: [[1, 40], uniform]
        beta: [[0,0.5], uniform]
        d: [[0,1], uniform]
        P_fatal: [[0, 0.5], uniform]
        I_hosp_ratio: [[0, 6.0], uniform]
        E_hosp_ratio: [[0, 2.0], uniform]
        Pu_pop_ratio: [[0,0.6], uniform]
    default_params:
        N: 1.0e+7
        psi: 1.0
    optimiser: BO_Hyperopt
    optimiser_params:
        num_evals: 1000
        algo: tpe
    split:
        start_date: null # NOT IMPLEMENTED
        end_date: null
        train_period: 28
        val_period: 28
        test_period: 0 # NOT IMPLEMENTED
        split_after_rolling: TRUE
    loss:
        loss_method: mape
        loss_compartments: [total, active, recovered, deceased]
        loss_weights: [0.25, 0.25, 0.25, 0.25]
sensitivity:
    lockdown_R0: [[[0.5, 1.5], 101], total, null]
    I_hosp_ratio: [[[0, 1], 201], total, null]
    E_hosp_ratio: [[[0, 2], 201], total, null]
    P_fatal: [[[0, 0.5], 201], deceased, total]
    T_recov: [[[1, 100], 101], recovered, total]
    T_recov_fatal: [[[1, 100], 101], deceased, total]
forecast:
        forecast_days: 30
plotting:
    truncate_series: TRUE
    left_truncation_buffer: 7
    right_truncation_buffer: forecast_days
    separate_compartments_separate_ax: TRUE
    num_trials_to_plot: 10
    pair_fits_to_plot: [[best, ensemble_mean], [ensemble_mean, 50], [50, 80]]
    plot_topk_trials_for_columns: [total, active, recovered, deceased]
    plot_ptiles_for_columns: [total, active, recovered, deceased]
uncertainty:
    method: ABMAUncertainty
    uncertainty_params:
        which_fit: m1
        fitting_method: gridsearch
        fitting_method_params:
            parallelise: FALSE
            n_jobs: 10
        variable_param_ranges:
            beta: [[0, 10], 101]
        construct_percentiles_day_wise: FALSE
        date_of_sorting_trials: 2020-11-30
        sort_trials_by_column: total
        loss:
            loss_method: mape
            loss_compartments: [total, active, recovered, deceased]
            loss_weights: [0.25, 0.25, 0.25, 0.25]
        percentiles: [2.5, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 97.5]
logging:
    experiment_name: wiai-temp
    run_name: null
