fitting:
    # Geographical Location
    state: 'Maharashtra'
    district: 'Mumbai'
    #Data
    data_from_tracker: False
    granular_data: True
    filename: None
    smooth_jump: TRUE
    #Choose Model and Ranges
    model: SEIRHD_Severity
    variable_param_ranges:  
        lockdown_R0: [1, 1.15]
        T_inc: [4, 5]
        T_inf: [3, 4]
        T_recov_mild: [20, 30]
        T_recov_moderate: [20, 30]
        T_recov_severe: [0, 40]
        P_moderate: [0, 0.5]
        P_severe: [0, 0.1]
        P_fatal: [0, 0.1]
        E_hosp_ratio: [0, 2]
        I_hosp_ratio: [0, 1]
    default_params:
        N: 1.0e+7
        lockdown_date: 2020-03-25
        lockdown_removal_date: 2020-06-30
    #Choose Fitting Periods and num evaluations
    train_period: 7
    val_period: 7
    test_period: 0
    num_evals: 1000
    initialisation: 'intermediate'
    #Optimisation related parameters
    which_compartments: ['total', 'active', 'recovered', 'deceased', 'stable_asymptomatic', 'stable_symptomatic', 'critical']
sensitivity:
    lockdown_R0: [[1, 1.5], 101, 'total', None]
    I_hosp_ratio: [[0, 1], 201, 'total', None]
    E_hosp_ratio: [[0, 2], 201, 'total', None]
    P_moderate: [[0, 0.5], 201, 'stable_symptomatic', 'total']
    P_severe: [[0, 0.5], 201, 'critical', 'total']
    P_fatal: [[0, 0.5], 201, 'deceased', 'total']
    T_recov_mild: [[1, 100], 101, 'stable_asymptomatic', 'total']
    T_recov_moderate: [[1, 100], 101, 'stable_symptomatic', 'total']
    T_recov_severe: [[1, 100], 101, 'critical', 'total']
    T_recov_fatal: [[1, 100], 101, 'deceased', 'total']
forecast:
    forecast_days: 30
    num_trials_to_plot: 10
    plot_topk_trials_for_columns: [confirmed, active, stable_symptomatic, stable_asymptomatic]
    plot_ptiles_for_columns: [confirmed, active, stable_symptomatic, stable_asymptomatic]
uncertainty:
    method: MCUncertainty
    uncertainty_params:
        num_evals: 100
        date_of_sorting_trials: 2020-07-31
        sort_trials_by_column: confirmed
        loss_compartments: ['total', 'active', 'recovered', 'deceased']

    
