fitting:
    # Geographical Location
    data:
        data_source: covid19india
        stratified_data: FALSE
        dataloading_params:
            state: Maharashtra
            district: Mumbai
            use_dataframe: data_all
        smooth_jump: FALSE
        smooth_jump_params:
            2020-05-28: [null, recovered, active, FALSE, weighted-mag]
            2020-06-14: [null, recovered, active, FALSE, weighted-mag]
            2020-06-15: [null, recovered, active, FALSE, weighted-mag]
            2020-06-23: [2020-06-15, recovered, active, FALSE, weighted-mag]
            2020-06-24: [2020-06-15, recovered, active, FALSE, weighted-mag]
            2020-07-01: [2020-05-28, recovered, active, FALSE, weighted-mag]
            2020-06-15: [null, deceased, total, TRUE, weighted-mag]
        rolling_average: TRUE
        rolling_average_params:
            center: TRUE
            window_size: 7
            win_type: null
            min_periods: 7
            split_after_rolling: FALSE
    #Choose Model and Ranges
    model: SEIRHD
    variable_param_ranges:
        lockdown_R0: [[0.7, 1.2], uniform]
        T_inc: [[3, 5], uniform]
        T_inf: [[3, 5], uniform]
        T_recov: [[1e-10, 40], uniform]
        T_recov_fatal: [[1e-10, 40], uniform]
        P_fatal: [[1e-10, 0.2], uniform]
        E_hosp_ratio: [[1e-10, 1], uniform]
        I_hosp_ratio: [[1e-10, 1], uniform]
        sigma: [[1, 3],uniform]
    default_params:
        N: 1.0e+7
    fitting_method: mcmc_opt

    fitting_method_params:
        proposal_sigmas:
            lockdown_R0: 0.04
            T_inc: 0.3
            T_inf: 0.1
            T_recov: .5
            T_recov_fatal: 2.5
            P_fatal: 0.01
            E_hosp_ratio: .05
            I_hosp_ratio: .05
            sigma: .02
        num_evals: 15000
        algo: gaussian
        n_chains: 4
        stride: 3
    #Choose Fitting Periods and num evaluations
    split:
        start_date: null
        end_date: 2020-10-26
        train_period: 21
        val_period: 7
        test_period: 0
    #Optimisation related parameters
    loss:
        loss_method: mape
        loss_compartments: [total, active, recovered, deceased]
        loss_weights: [0.25, 0.25, 0.25, 0.25]
sensitivity:
    lockdown_R0: [[[0.5, 1.5], 101], total, null]
    I_hosp_ratio: [[[0, 1], 201], total, null]
    E_hosp_ratio: [[[0, 2], 201], total, null]
    P_fatal: [[[0, 0.5], 201], deceased, total]
    T_recov: [[[1, 100], 101], recovered, total]
    T_recov_fatal: [[[1, 100], 101], deceased, total]
forecast:
    forecast_days: 30
    num_trials_to_plot: 10
    plot_topk_trials_for_columns: [total, active]
    plot_ptiles_for_columns: [total, active]
uncertainty:
    method: MCMCUncertainty
    uncertainty_params:
        num_evals: 100
        which_fit: m1
        variable_param_ranges:
            beta: [[0, 10], uniform]
        date_of_sorting_trials: 2020-10-26
        sort_trials_by_column: total
        loss:
            loss_method: mape
            loss_compartments: [total, active, recovered, deceased]
            loss_weights: [0.25, 0.25, 0.25, 0.25]
        percentiles: [ 1.        ,  3.51282051,  6.02564103,  8.53846154, 11.05128205,
       13.56410256, 16.07692308, 18.58974359, 21.1025641 , 23.61538462,
       26.12820513, 28.64102564, 31.15384615, 33.66666667, 36.17948718,
       38.69230769, 41.20512821, 43.71794872, 46.23076923, 48.74358974,
       51.25641026, 53.76923077, 56.28205128, 58.79487179, 61.30769231,
       63.82051282, 66.33333333, 68.84615385, 71.35897436, 73.87179487,
       76.38461538, 78.8974359 , 81.41025641, 83.92307692, 86.43589744,
       88.94871795, 91.46153846, 93.97435897, 96.48717949, 99.        ]