fitting:
    # Geographical Location
    data:
        data_source: covid19india
        stratified_data: FALSE
        dataloading_params:
            state: Maharashtra
            district: Mumbai
            use_dataframe: data_all
        smooth_jump: FALSE
        smooth_jump_params:
            2020-05-28: [null, recovered, active, FALSE, weighted-mag]
            2020-06-14: [null, recovered, active, FALSE, weighted-mag]
            2020-06-15: [null, recovered, active, FALSE, weighted-mag]
            2020-06-23: [2020-06-15, recovered, active, FALSE, weighted-mag]
            2020-06-24: [2020-06-15, recovered, active, FALSE, weighted-mag]
            2020-07-01: [2020-05-28, recovered, active, FALSE, weighted-mag]
            2020-06-15: [null, deceased, total, TRUE, weighted-mag]
        rolling_average: TRUE
        rolling_average_params:
            center: TRUE
            window_size: 7
            win_type: null
            min_periods: 7
            split_after_rolling: FALSE
    #Choose Model and Ranges
    model: SEIRHD
    variable_param_ranges:
        lockdown_R0: [[0.7, 1.2], uniform]
        T_inc: [[3, 5], uniform]
        T_inf: [[3, 5], uniform]
        T_recov: [[1e-10, 40], uniform]
        T_recov_fatal: [[1e-10, 40], uniform]
        P_fatal: [[1e-10, 0.2], uniform]
        E_hosp_ratio: [[1e-10, 1], uniform]
        I_hosp_ratio: [[1e-10, 1], uniform]
        gamma: [[1, 3],uniform]
    default_params:
        N: 1.0e+7
    fitting_method: mcmc_opt

    fitting_method_params:
        proposal_sigmas:
            lockdown_R0: 0.08
            T_inc: 0.6
            T_inf: 0.2
            T_recov: 1
            T_recov_fatal: 5
            P_fatal: 0.02
            E_hosp_ratio: .1
            I_hosp_ratio: .1
            gamma: .04
        num_evals: 15000
        algo: gaussian
        n_chains: 4
        stride: 3
    #Choose Fitting Periods and num evaluations
    split:
        start_date: null
        end_date: 2020-10-26
        train_period: 21
        val_period: 7
        test_period: 0
    #Optimisation related parameters
    loss:
        loss_method: mape
        loss_compartments: [total, active, recovered, deceased]
        loss_weights: [0.25, 0.25, 0.25, 0.25]
sensitivity:
    lockdown_R0: [[[0.5, 1.5], 101], total, null]
    I_hosp_ratio: [[[0, 1], 201], total, null]
    E_hosp_ratio: [[[0, 2], 201], total, null]
    P_fatal: [[[0, 0.5], 201], deceased, total]
    T_recov: [[[1, 100], 101], recovered, total]
    T_recov_fatal: [[[1, 100], 101], deceased, total]
forecast:
    forecast_days: 30
    num_trials_to_plot: 10
    plot_topk_trials_for_columns: [total, active]
    plot_ptiles_for_columns: [total, active]
uncertainty:
    method: MCUncertainty
    uncertainty_params:
        which_fit: m1
        fitting_type: mcmc
        fitting_method: gridsearch
        fitting_method_params:
            parallelise: FALSE
        variable_param_ranges:
            beta: [[0, 10], 101]
        construct_percentiles_day_wise: TRUE
        date_of_sorting_trials: 2020-10-26
        sort_trials_by_column: total
        loss:
            loss_method: mape
            loss_compartments: [total, active, recovered, deceased]
            loss_weights: [0.25, 0.25, 0.25, 0.25]
        percentiles: [2.5, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 97.5]