fitting:
    # Geographical Location
    data:
        dataloader: Covid19IndiaLoader
        stratified_data: FALSE
        dataloading_params:
            reload_data: FALSE
            cache_dir: "../../misc/cache/"
            state: Maharashtra
            district: Mumbai
            use_dataframe: data_all
        smooth_jump: TRUE
        smooth_jump_params:
            2020-05-28: [null, recovered, active, FALSE, weighted-mag]
            2020-06-14: [null, recovered, active, FALSE, weighted-mag]
            2020-06-15: [null, recovered, active, FALSE, weighted-mag]
            2020-06-23: [2020-06-15, recovered, active, FALSE, weighted-mag]
            2020-06-24: [2020-06-15, recovered, active, FALSE, weighted-mag]
            2020-07-01: [2020-05-28, recovered, active, FALSE, weighted-mag]
            2020-06-15: [null, deceased, total, TRUE, weighted-mag]
        rolling_average: TRUE
        rolling_average_params:
            center: TRUE
            window_size: 7
            win_type: null
            min_periods: 1
            split_after_rolling: TRUE
    #Choose Model and Ranges
    model_family: seir
    model: SEIR_Undetected
    variable_param_ranges:
        T_inc: [[4, 6], uniform]
        T_inf_D: [[3, 5], uniform]
        T_inf_U: [[4, 6], uniform]
        T_recov_severe: [[0, 40], uniform]
        T_recov_fatal: [[0, 40], uniform]
        P_fatal: [[0, 0.5], uniform]
        E_hosp_ratio: [[0, 2], uniform]
        I_D_hosp_ratio: [[0, 1], uniform]
        I_U_hosp_ratio: [[0, 1], uniform]
        d: [[0,1], uniform]
        beta: [[0,1], uniform]
    default_params:
        N: 1.0e+7
        psi: 1.0
        lockdown_date: 2020-03-25
        lockdown_removal_date: 2020-08-30
    fitting_method: BO_Hyperopt
    fitting_method_params:
        num_evals: 1000
        algo: tpe
        seed: 42
    #Choose Fitting Periods and num evaluations
    split:
        start_date: null
        end_date: null
        train_period: 21
        val_period: 14
        test_period: 0
    #Optimisation related parameters
    loss:
        loss_method: mape
        loss_compartments: [total, active, recovered, deceased]
        loss_weights: [0.25, 0.25, 0.25, 0.25]
forecast:
        forecast_days: 30
plotting:
    truncate_series: TRUE
    left_truncation_buffer: 7
    right_truncation_buffer: forecast_days
    separate_compartments_separate_ax: TRUE
    num_trials_to_plot: 10
    plot_topk_trials_for_columns: [total, active, recovered, deceased]
    plot_ptiles_for_columns: [total, active, recovered, deceased]
uncertainty:
    method: ABMAUncertainty
    uncertainty_params:
        which_fit: m1
        fitting_method: gridsearch
        fitting_method_params:
            parallelise: FALSE
            n_jobs: 10
        variable_param_ranges:
            beta: [[0, 10], 101]
        construct_percentiles_day_wise: TRUE
        date_of_sorting_trials: 2020-09-30
        sort_trials_by_column: total
        loss:
            loss_method: mape
            loss_compartments: [total, active, recovered, deceased]
            loss_weights: [0.25, 0.25, 0.25, 0.25]
        percentiles: [2.5, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 97.5]
