model: SEIR_PU
starting_date: 2020-08-18
total_days: 75
initial_values:
    recovered: 95000
    deceased: 7500
    active: 20000
include_tests: True
tests_done: '[10000 for i in range(75)]'
fix_params: True
params:
    N: 2.0e+7
    T_inc: 4.5
    T_inf_U: 10
    T_recov: 10
    T_recov_fatal: 10 
    beta: 0.18
    d: 0.2
    P_fatal: 0.2
    I_hosp_ratio: 1.2
    E_hosp_ratio: 1.5
    Pu_pop_ratio: 0.3
output_file_name: seir_pu_fixed_1.csv