model: SEIRHD
starting_date: 2020-08-18
total_days: 50
initial_values:
    recovered: 95000
    deceased: 7500
    active: 20000
include_tests: True
tests_done: '[10000 for i in range(50)]'
fix_params: False
params:
    N: 1.0e+7
    lockdown_R0: [[0.6, 1.2], uniform]
    T_inc: [[4, 6], uniform]
    T_inf: [[3, 4], uniform]
    T_recov: [[0, 40], uniform]
    T_recov_fatal: [[0, 40], uniform]
    P_fatal: [[0, 0.5], uniform]
    E_hosp_ratio: [[0, 2], uniform]
    I_hosp_ratio: [[0, 2], uniform]
output_file_name: simulated_data_1.csv
