model: SEIR_PU
starting_date: 2020-08-18
total_days: 75
initial_values:
    recovered: 95000
    deceased: 7500
    active: 20000
include_tests: True
tests_done: '[10000 for i in range(75)]'
fix_params: False
params:
    N: 2.0e+7
    T_inc: [[4, 6], uniform]
    T_inf_U: [[7, 12], uniform]
    T_recov: [[13, 17], uniform]
    T_recov_fatal: [[20, 30], uniform]
    beta: [[0.1, 0.4], uniform]
    d: [[0.1,0.3], uniform]
    P_fatal: [[0.02, 0.05], uniform]
    I_hosp_ratio: [[0.5, 1.5], uniform]
    E_hosp_ratio: [[0.7, 1.7], uniform]
    Pu_pop_ratio: [[0.3, 0.45], uniform]
output_file_name: simulated_data_1.csv