model: SEIRHD
starting_date: 2020-07-12
total_days: 50
initial_values:
    recovered: [[50000, 100000], uniform]
    deceased: 7500
    active: [[50000, 100000], uniform]
fix_params: FALSE
set_seed: FALSE
seed: null
params:
    N: 1.0e+7
    lockdown_R0: [[0.6, 1.2], uniform]
    T_inc: [[4, 6], uniform]
    T_inf: [[3, 4], uniform]
    T_recov: [[0, 40], uniform]
    T_recov_fatal: [[0, 40], uniform]
    P_fatal: [[0, 0.5], uniform]
    E_hosp_ratio: [[0, 2], uniform]
    I_hosp_ratio: [[0, 2], uniform]
save: FALSE
output_file_name: simulated_data_1.csv 