model: SEIR_PU
starting_date: 2020-08-18
total_days: 75
initial_values:
    recovered: 95000
    deceased: 7500
    active: 20000
include_tests: True
tests_done: '[10000 for i in range(75)]'
fix_params: True
params:
    N: 2.0e+7
    T_inc: 4.5
    T_inf_U: 10
    T_recov: 15
    T_recov_fatal: 25 
    beta: 0.25
    d: 0.2
    P_fatal: 0.3
    I_hosp_ratio: 0.5
    E_hosp_ratio: 0.5
    Pu_pop_ratio: 0.1
output_file_name: seir_pu_fixed.csv