model: SEIRHD_Beta
starting_date: 2020-01-01
total_days: 400
initial_values:
    recovered: 0
    deceased: 0
    active: 5
fix_params: True
params:
    N: 1.0e+7
    beta: 0.25
    T_inc: 5.1
    T_inf: 6.6
    T_recov: 14
    T_recov_fatal: 10 
    P_fatal: 0.03
    E_hosp_ratio: 1.0
    I_hosp_ratio: 1.0
output_file_name: simulated_data_2.csv 