base:
  district: Pune
  state: Maharashtra
  disable_tracker: TRUE
  use_synthetic: TRUE
  use_actual: TRUE
  allowance: 5
  s1: 10
  s2: 5
  s3: 7
  shift: 0
  i1_val_size: 3
  c2_train_period: 5
  c3_train_period: 7

